package com.projectlab.feature.onboarding.presentation.ui

import androidx.compose.ui.geometry.Size
import androidx.compose.ui.graphics.painter.Painter
import androidx.compose.ui.graphics.drawscope.DrawScope
import org.junit.Assert.*
import org.junit.Test



class OnboardingPageTest {

    // Empty painter to use in tests
    private val dummyPainter: Painter = object : Painter() {
        override val intrinsicSize: Size
            get() = Size.Unspecified

        override fun DrawScope.onDraw() {
            // this doesn't draw anything
        }
    }

    @Test
    fun `data class equality OnboardingPage`() {
        val page1 = OnboardingPage(
            title = "T1",
            description = "D1",
            backgroundImage = dummyPainter
        )
        val page2 = OnboardingPage(
            title = "T1",
            description = "D1",
            backgroundImage = dummyPainter
        )

        // We check that instances with the same values are equal
        assertEquals(page1, page2)
        // We check that hashCode by consistent using the same values
        assertEquals(page1.hashCode(), page2.hashCode())
    }

    @Test
    fun `toString contains values`() {
        val page = OnboardingPage("Hello", "Desc", dummyPainter)
        val str = page.toString()

        // toString generated by the data class must include the title and description values.
        assertTrue(str.contains("Hello"))
        assertTrue(str.contains("Desc"))
    }


}